version: "3.3"
services:
  web:
    image: "lanyanxi/habits-restapi"
    container_name: habits-restapi
    environment:
      - REDIS_URI=redis://cache
    ports:
      - "80:5000"
    env_file:
      - ./.env
#  mongo:
#    image: "mongo:alpine"
#    container_name: database
#    expose:
#      - "27017"
  redis:
    image: "redis:alpine"
    container_name: cache
    expose:
      - "6379"
#  nginx:
#    image: nginx.image.uri:latest
#    ports:
#      - "80:80"
#    links: # new
#      - web
#    volumes_from:
#      - web
