# This GitHub action will deploy the current code to a container optimized
# compute instance.
name: CD-Kubectl Instance
on:
  push:
    branches:
      - master
      - feature/cd-test
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: "Set up gcloud"
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud -v
      - run: gcloud info
      - run: gcloud config set compute/zone ${{ secrets.GCP_ZONE }}

      - name: "Perform ssh"
        run: gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }}

      - name: "Clone repo if not exist"
        run: [ ! -d "habits-restapi" ] && git clone https://github.com/lanyanxiang/habits-restapi.git habits-restapi

      - name: "Run git pull"
        run: cd habits-cli && git pull
